### ISSUE TITLE
Helm charts

### ISSUE THREAD

**Issue by nvanheuverzwijn** [upmc-enterprises/registry-creds#71]
Did you guys ever considered building an helm chart and have it graduated to https://github.com/helm/charts/tree/master/stable/ ?

I have done one for your project here : https://github.com/kronostechnologies/helm-chart-awscred

**Comment by stevesloka** [comment]
Hey @nvanheuverzwijn! I never personally got into using Helm as a tool in my pocket (not that other's can't, just my personal experience). Happy to bring something in if you'd like to send a PR. =)

**Comment by nvanheuverzwijn** [comment]
@stevesloka Seems like there is a chart in helm hub : https://hub.helm.sh/charts/kir4h/registry-creds
The charts looks very good. Maybe we could update the README to use it ?

**Comment by nvanheuverzwijn** [comment]
The github source : https://github.com/kir4h/charts/tree/master/charts/registry-creds
