### ISSUE TITLE
Newly published registry-creds image (1.10) does not contain ACR (Azure) support

### ISSUE THREAD

**Issue by karolz-ms** [upmc-enterprises/registry-creds#85]
Repro steps:

1. Install the registry-creds controller following standard instructions
1. Deploy the controller
1. Attach a shell to the controller container
1. Run `strings -n 9 registry-creds | grep acrClient`

Expected: a bunch of strings that have 'acrClient' in them
Actual: nothing

For comparison, this is the result of running the same command on zpkarol/registry-creds:1.10 image that I have build for testing (it is available from Docker Hub):

```
karolz:~/ strings -n 9 registry-creds | grep acrClient
acrClient
*main.acrClient
main.acrClient.getAuthToken
main.(*acrClient).getAuthToken
main.acrClient.getAuthToken.stkobj
go.itab.main.acrClient,main.acrInterface
main.acrClient.getAuthToken
main.(*acrClient).getAuthToken
```

Looks like incorrect (old) binary was included in the 1.10 image? @stevesloka could you take a look? Thanks!

**Comment by karolz-ms** [comment]
Hey @stevesloka @oliverspryn do you guys have a timeframe for investigating this issue? 

I double-checked the image again and I am pretty sure the binary inside does not have support for Azure 😞

**Comment by stevesloka** [comment]
Let me take a look this afternoon @karolz-ms

**Comment by stevesloka** [comment]
Hey @karolz-ms can you re-pull the image? I just rebuild it all again. Thanks!

**Comment by karolz-ms** [comment]
It works! 😌 Many thanks, @stevesloka
